### ISSUE TITLE
Is this project supposed to be run under Windows?

### ISSUE THREAD

**Issue by chengtie** [nmaoez/composer-language-server#4]
I'm trying this project on my Mac.

I have already "Clone project" and "Import as Gradle project into Eclipse". However, I tried to run `.\gradlew.bat clean build` in the terminal, it gave me `.gradlew.bat: command not found`.

Is this project supposed to be run under Windows?

Cheers

**Comment by nmaoez** [comment]
Since `gradlew.bat` is a batch-file, it is only executable on Windows machines. See [here](https://stackoverflow.com/questions/44860306/what-is-gradle-wrapper-and-gradlew-bat-file). On Mac i guess you have to execute the `gradlew`-file. I updated the readme.
